name: WormGPT_Run
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install pyTelegramBotAPI requests
      - name: Start Bot
        run: python main.py
        
